run:
  allow-parallel-runners: true
  go: '1.20'

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustivestruct
    - nonamedreturns
    - testpackage
    - exhaustruct
    - exhaustive
    - varnamelen
    - depguard
    - gci

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
    enable-all: true
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: pkg/client/http.go
      text: "G402" # G402: TLS InsecureSkipVerify set true.
      linters:
        - gosec
    - path: ._test\.go
      linters:
        - dupword
        - ifshort
        - cyclop
        - funlen
    - path: cmd/crawley/main.go
      linters:
        - nakedret
