run:
  go: '1.19'

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustivestruct
    - nonamedreturns
    - testpackage
    - exhaustruct
    - exhaustive
    - varnamelen
    - forbidigo
    - gofumpt
    - gci
  fast: false

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: pkg/client/http.go
      text: "G402" # G402: TLS InsecureSkipVerify set true.
      linters:
        - gosec
    - path: ._test\.go
      linters:
        - goerr113
        - errcheck
        - dupword
        - ifshort
        - cyclop
        - funlen
        - dupl
