run:
  allow-parallel-runners: true

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - nonamedreturns
    - testpackage
    - exhaustruct
    - tagliatelle
    - exhaustruct
    - inamedparam
    - exhaustive
    - varnamelen
    - intrange
    - depguard
    - ireturn
    - gofumpt
    - gci

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  cyclop:
    max-complexity: 15
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: internal/client/http.go
      text: "G402" # G402: TLS InsecureSkipVerify set true.
      linters:
        - gosec
    - path: ._test\.go
      linters:
        - canonicalheader
        - dupword
        - ifshort
        - cyclop
        - funlen
        - dupl
    - path: cmd/crawley/main.go
      linters:
        - nakedret
