linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - gochecknoglobals
    - nonamedreturns
    - testpackage
    - exhaustive
    - exhaustruct
    - varnamelen
    - forbidigo
    - typecheck
    - gofumpt
    - gci
    # deprecated :(
    - interfacer
    - scopelint
    - maligned
    - golint
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: pkg/client/http.go
      text: "G402" # G402: TLS InsecureSkipVerify set true.
      linters:
        - gosec
    - path: ._test\.go
      linters:
        - funlen
        - ifshort
        - cyclop
        - dupl
        - goerr113
        - errcheck
