# .goreleaser.yml
project_name: crawley

before:
  hooks:
    - go mod download

builds:
  - id: "crawley"
    dir: .
    main: ./cmd/crawley
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
      - -X main.GitTag={{.Tag}}
      - -X main.GitHash={{.ShortCommit}}
      - -X main.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

changelog:
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^refactor'
      - '^style'
      - '^test'
