# release workflow
name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: set up golang
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: build
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          distribution: goreleaser
          args: release -f .goreleaser.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
